PFCharacterCreator/PFCharacterCreator/urls.py
from django.contrib import admin
from django.urls import path
from main import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('', views.index, name="index"),
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name="login_url"),
    path('logout/', LogoutView.as_view(), name="logout_url"),
    path('register/', views.registrar_usuario, name="registrar_usuario_url"),
    path('paginaError/', views.error, name="error_url"),
    path('gdpr/', views.gdpr, name="gdpr_url"),
    path('raza/list/', views.listar_razas, name='listar_razas_url'),
    path('dote/list/', views.listar_dotes, name='listar_dotes_url'),
    path('dote/perfil/list/', views.listar_dotes_propias, name='listar_dotes_url'),
    path('clase/list/', views.listar_clases, name='listar_clases_url'),
    path('conjuro/list/<int:pk>/', views.listar_conjuros_por_clase, name='listar_conjuros_por_clase_url'),
    path('habilidad/list/', views.listar_habilidades, name='listar_habilidades_url'),
    path('poder/list/<int:pk>/', views.listar_poderes_por_clase, name='listar_poderes_por_clase_url'),
    path('especial/list/<int:pk>/', views.listar_especiales_por_clase, name='listar_especiales_por_clase_url'),
    path('companero_animal/list/', views.listar_companeros_animales, name='listar_companeros_animales_url'),
    path('truco/list/', views.listar_trucos, name='listar_trucos_url'),
    path('propiedad/list/', views.listar_propiedades, name='listar_propiedades_url'),
    path('linaje/list/', views.listar_linajes, name='listar_linajes_url'),
    path('objeto/list/', views.listar_objetos, name='listar_objetos_url'),
    path('personaje/list/', views.listar_personajes_publicos, name='listar_personajes_publicos_url'),
    path('personaje/perfil/list/', views.listar_personajes_propios, name='listar_personajes_propios_url'),
    path('raza/show/<int:pk>/', views.mostrar_raza, name='mostrar_raza_url'),
    path('dote/show/<int:pk>/', views.mostrar_dote, name='mostrar_dote_url'),
    path('clase/show/<int:pk>/', views.mostrar_clase, name='mostrar_clase_url'),
    path('conjuro/show/<int:pk>/', views.mostrar_conjuro, name='mostrar_conjuro_url'),
    path('poder/show/<int:pk>/', views.mostrar_poder, name='mostrar_poder_url'),
    path('companero_animal/show/<int:pk>/', views.mostrar_companero_animal, name='mostrar_companero_animal_url'),
    path('truco/show/<int:pk>/', views.mostrar_truco, name='mostrar_truco_url'),
    path('propiedad/show/<int:pk>/', views.mostrar_propiedad, name='mostrar_propiedad_url'),
    path('linaje/show/<int:pk>/', views.mostrar_linaje, name='mostrar_linaje_url'),
    path('objeto/show/<int:pk>/', views.mostrar_objeto, name='mostrar_objeto_url'),
    path('personaje/show/<int:pk>/', views.mostrar_personaje, name='mostrar_personaje_url'),
    path('companero_animal_personaje/show/<int:pk>/', views.mostrar_companero_animal_personaje, name='mostrar_companero_animal_personaje_url'),
    path('perfil/', views.mostrar_perfil_propio, name='mostrar_perfil_propio_url'),
    path('perfil/show/<int:pk>', views.mostrar_perfil, name='mostrar_perfil_url'),
    path('personaje/publico/<int:pk>/', views.cambiar_personaje_a_publico, name='cambiar_personaje_a_publico_url'),
    path('personaje/privado/<int:pk>/', views.cambiar_personaje_a_privado, name='cambiar_personaje_a_privado_url'),
    path('dote/create/', views.crear_dote, name='crear_dote_url'),
    path('dote/edit/<int:pk>/', views.editar_dote, name='editar_dote_url'),
    path('dote/delete/<int:pk>/', views.eliminar_dote, name='eliminar_dote_url'),
    path('perfil/edit/usuario/', views.editar_usuario, name='editar_usuario_url'),
    path('perfil/edit/contrasena/', views.editar_contrasena, name='editar_contrasena_url'),
    path('perfil/edit/', views.editar_perfil, name='editar_perfil_url'),
    path('perfil/delete/', views.eliminar_usuario, name='eliminar_usuario_url'),
    path('dote/search/', views.buscar_dote, name='buscar_dote_url'),
    path('poder/search/<int:pk>/', views.buscar_poder, name='buscar_poder_url'),
    path('conjuro/search/<int:pk>/', views.buscar_conjuro, name='buscar_conjuro_url'),
    path('personaje/search/', views.buscar_personaje, name='buscar_personaje_url'),
    path('personaje/create/', views.crear_personaje_1, name='crear_personaje_1_url'),
    path('personaje/create/2/', views.crear_personaje_2, name='crear_personaje_2_url'),
    path('personaje/create/3/', views.crear_personaje_3, name='crear_personaje_3_url'),
    path('personaje/companero_animal/asignar/<int:pk>/', views.asignar_companero_animal, name='asignar_companero_animal_url'),
    path('personaje/delete/<int:pk>/', views.eliminar_personaje, name='eliminar_personaje_url'),
    path('personaje/subir_nivel/<int:pk>/', views.subir_nivel, name='subir_nivel_url'),
    path('json/<int:pk>/', views.json),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

PFCharacterCreator/main/models.py
from django.db import models
from django.contrib.auth.models import User
import math

# Create your models here.
class Perfil(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE, null=False)
    nickname = models.TextField(verbose_name='Nickname')
    es_admin = models.BooleanField(verbose_name='Admin', default=False)

    def __str__(self):
        return self.usuario.username

    class Meta:
        ordering = ('pk', )

class Personaje(models.Model):
    perfil = models.ForeignKey('Perfil', on_delete=models.CASCADE, null=False)
    nombre = models.TextField(verbose_name='Nombre')
    
    class Alineamiento(models.TextChoices):
        LB = 'LB', 'Legal Bueno'
        LN = 'LN', 'Legal Neutral'
        LM = 'LM', 'Legal Malo'
        NB = 'NB', 'Neutral Bueno'
        N = 'N', 'Neutral'
        NM = 'NM', 'Neutral Malo'
        CB = 'CB', 'Caótico Bueno'
        CN = 'CN', 'Caótico Neutral'
        CM = 'CM', 'Caótico Malo'
    alineamiento = models.CharField(verbose_name='alineamiento', 
    max_length=2, choices=Alineamiento.choices, null=True)
    puntos_de_golpe = models.IntegerField(verbose_name='Puntos de golpe',
    null=True)
    resistencia_dano = models.IntegerField(verbose_name='Resistencia al daño',
    null=True)
    resistencia_conjuros = models.IntegerField(verbose_name='Resistencia a Conjuros',
    null=True)
    fuerza = models.IntegerField(verbose_name='Fuerza', default=10)
    destreza = models.IntegerField(verbose_name='Destreza', default=10)
    constitucion = models.IntegerField(verbose_name='Constitución',
     default=10)
    inteligencia = models.IntegerField(verbose_name='Inteligencia',
     default=10)
    sabiduria = models.IntegerField(verbose_name='Sabiduría',
     default=10)
    carisma = models.IntegerField(verbose_name='Carisma', default=10)
    dinero = models.FloatField(verbose_name='Dinero', default=0.0)
    es_publico = models.BooleanField(verbose_name='Es público', default=False)
    idiomas = models.ManyToManyField('Idioma')
    raza = models.ForeignKey('Raza', on_delete=models.CASCADE, null=True)
    clase = models.ForeignKey('Clase', on_delete=models.CASCADE, null=True)
    dotes = models.ManyToManyField('Dote')
    puntuaciones_habilidad = models.ManyToManyField('PuntuacionHabilidad')
    conjuros_conocidos = models.ManyToManyField('Conjuro')
    poderes_conocidos = models.ManyToManyField('Poder')
    linaje = models.ForeignKey('Linaje', null=True, on_delete=models.SET_NULL)

    @property
    def bonificadorFuerza(self):
        return math.floor((self.fuerza-10)/2)
    
    @property
    def bonificadorDestreza(self):
        return math.floor((self.destreza-10)/2)

    @property
    def bonificadorConstitucion(self):
        return math.floor((self.constitucion-10)/2)

    @property
    def bonificadorInteligencia(self):
        return math.floor((self.inteligencia-10)/2)

    @property
    def bonificadorSabiduria(self):
        return math.floor((self.sabiduria-10)/2)

    @property
    def bonificadorCarisma(self):
        return math.floor((self.carisma-10)/2)
    
    @property
    def iniciativa(self):
        return self.bonificadorDestreza

    @property
    def carga_ligera(self):
        carga_ligera = 0.0
        libra = 0.45
        diccionario = {10:33, 11:38, 12:43, 13:50, 14:58, 15:66, 16:76, 17:86, 18:100, 19:116}
        if self.fuerza < 10:
            carga_ligera = self.fuerza * 3.33
        elif self.fuerza >= 10 and self.fuerza <= 19:
            carga_ligera = diccionario.get(self.fuerza) * libra
        elif self.fuerza > 19:
            carga_ligera = diccionario.get(self.fuerza%10+10) * libra * 4
        if self.raza.tamano == 'Pequeño':
            carga_ligera = carga_ligera/2
        return round(carga_ligera, 2)
    
    @property
    def carga_media(self):
        return self.carga_ligera * 2
    
    @property
    def carga_maxima(self):
        return self.carga_media * 2

    @property
    def clase_armadura(self):
        clase_armadura = 10
        clase_armadura = clase_armadura + self.clase.bonificacion_ac + self.bonificadorDestreza
        return clase_armadura
    
    @property
    def desprevenido(self):
        desprevenido = 10
        desprevenido = desprevenido + self.clase.bonificacion_ac
        return desprevenido

    @property
    def toque(self):
        toque = 10
        toque = toque + self.bonificadorDestreza
        return toque

    @property
    def bmc(self):
        ataque_base_sum = 0
        ataque_base_sum = ataque_base_sum + self.clase.ataque_base_int
        bmc = '+' + str(ataque_base_sum + self.bonificadorFuerza)
        return bmc

    @property
    def dmc(self):
        ataque_base_sum = 0
        ataque_base_sum = ataque_base_sum + self.clase.ataque_base_int
        dmc = 10 + ataque_base_sum + self.bonificadorFuerza + self.bonificadorDestreza
        return dmc
    
    @property
    def fortaleza(self):
        fortaleza = 0
        fortaleza = fortaleza + self.clase.fortaleza
        fortaleza = fortaleza + self.bonificadorConstitucion
        return fortaleza
    
    @property
    def reflejos(self):
        reflejos = 0
        reflejos = reflejos + self.clase.reflejos
        reflejos = reflejos + self.bonificadorDestreza
        return reflejos

    @property
    def voluntad(self):
        voluntad = 0
        voluntad = voluntad + self.clase.voluntad
        voluntad = voluntad + self.bonificadorSabiduria
        return voluntad

    @property
    def ataque_base(self):
        ataque_base_sum = 0
        ataque_base = '+'
        ataque_base_sum = ataque_base_sum + self.clase.ataque_base_int
        if ataque_base_sum >= 6:
            while ataque_base_sum >= 6:
                ataque_base = ataque_base + str(ataque_base_sum) + '/'
                ataque_base_sum = ataque_base_sum - 5
            ataque_base = ataque_base + str(ataque_base_sum)
        else:
            ataque_base = ataque_base + str(ataque_base_sum)
        return ataque_base

    @property
    def nivel(self):
        nivel = 0
        nivel = nivel + self.clase.nivel
        return nivel
    
    @property
    def habilidades(self):
        for ph in self.puntuaciones_habilidad:
           habilidades[ph.habilidad.habilidad] = ph.puntuacion
        return habilidades

    def __str__(self):
        return self.nombre
    
    class Meta:
        ordering = ('pk', )

class Idioma(models.Model):
    idioma = models.TextField(verbose_name='Idioma')

    def __str__(self):
        return self.idioma

    class Meta:
        ordering = ('pk', )

class Raza(models.Model):
    raza = models.TextField(verbose_name='Raza')
    tamano = models.TextField(verbose_name='Tamaño', null=True)
    velocidad = models.TextField(verbose_name='Velocidad', null=True)
    fuerza = models.IntegerField(verbose_name='Fuerza', default=0)
    destreza = models.IntegerField(verbose_name='Destreza', default=0)
    constitucion = models.IntegerField(verbose_name='Constitución',default=0)
    inteligencia = models.IntegerField(verbose_name='Inteligencia', default=0)
    sabiduria = models.IntegerField(verbose_name='Sabiduría', default=0)
    carisma = models.IntegerField(verbose_name='Carisma', default=0)
    idiomas_conocidos = models.TextField(verbose_name='Idiomas conocidos', null=True)
    descripcion = models.TextField(verbose_name='Descripción', null=True)
    imagen = models.ImageField(upload_to='', verbose_name='Imagen', null=True)
    imagen_completa = models.ImageField(upload_to='', verbose_name='Imagen completa', null=True)
    idiomas_eleccion = models.ManyToManyField('Idioma')
    idiomas_iniciales = models.ManyToManyField('Idioma',related_name='idiomas_iniciales')
    bonificaciones_raza = models.ManyToManyField('BonificacionRaza')

    def __str__(self):
        return self.raza

    class Meta:
        ordering = ('raza', )

class BonificacionRaza(models.Model):
    nombre = models.TextField(verbose_name='Nombre', null=True)
    descripcion = models.TextField(verbose_name='Descripción', null=True)

    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ('pk', )

class PuntuacionHabilidad(models.Model):
    puntuacion = models.IntegerField(verbose_name='Puntuación',
    null=True)
    habilidad = models.ForeignKey('Habilidad', on_delete=models.CASCADE)

    def __str__(self):
        return self.habilidad.habilidad
        
    class Meta:
        ordering = ('pk', )

class Habilidad(models.Model):
    habilidad = models.TextField(verbose_name='Habilidad')
    caracteristica = models.TextField(verbose_name='Característica', null=True)
    es_habilidad_companero_animal = models.BooleanField(verbose_name='Es habilidad de compañero animal', default=False)

    def __str__(self):
        return self.habilidad

    class Meta:
        ordering = ('habilidad', )

class Clase(models.Model):
    clase = models.TextField(verbose_name='Clase')
    nivel = models.IntegerField(verbose_name='Nivel', default=0)
    dados_de_golpe = models.IntegerField(verbose_name='Dados de golpe', 
    default=6, null=True)
    ataque_base = models.TextField(verbose_name='Ataque base', 
    null=True)
    ataque_base_int = models.IntegerField(verbose_name='Ataque base', null=False, default=0)
    fortaleza = models.IntegerField(verbose_name='Fortaleza', 
    null=True)
    reflejos = models.IntegerField(verbose_name='Reflejos', null=True)
    voluntad = models.IntegerField(verbose_name='Fortaleza', null=True)
    competencia = models.TextField(verbose_name='Competente con', null=True)
    rafaga_de_golpes = models.TextField(verbose_name='Ráfaga de golpes', null=True)
    dano_desarmado = models.TextField(verbose_name='Daño desarmado', null = True)
    bonificacion_ac = models.IntegerField(verbose_name='Bonificación AC', null = True, default=0)
    movimiento_rapido = models.IntegerField(verbose_name='Movimiento rápido', null =True)

PFCharacterCreator/main/templates/perfil/edit.html
{% extends 'base.html' %}
{% block content %}
<div class="bottom-footer">
    <div class="container">
      <div class="row">
          <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto ">
                <h1 class="display-4 py-2 text-center">Editar usuario</h1>
                {% if form_editar_username.errors %}
                    {% for field in form_editar_username %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger text-center">
                                {{error}}
                            </div>
                        {% endfor %}
                    {% endfor %}
                {% endif %}
                {% if form_editar_contrasena.errors %}
                    {% for field in form_editar_contrasena %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger text-center">
                                {{error}}
                            </div>
                        {% endfor %}
                    {% endfor %}
                {% endif %}
                {% if form_editar_perfil.errors %}
                    {% for field in form_editar_perfil %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger text-center">
                                {{error}}
                            </div>
                        {% endfor %}
                    {% endfor %}
                {% endif %}
                <div class="px-2">
                    <form  role="form"  enctype="multipart/form-data" action="" method="POST" id="upload-image-form"> 
                        {% csrf_token %}
                        {% if form_editar_username %}
                        <div class="text-center">Nombre de Usuario</div>
                            {{form_editar_username.username}}
                            <br>
                        {% endif %}
                        {% if form_editar_contrasena %}
                        <div class="text-center">Contraseña</div>
                            {{form_editar_contrasena.password1}}
                            <br>
                        <div class="text-center">Confirmar Contraseña</div>
                            {{form_editar_contrasena.password2}}
                            <br>
                        {% endif %}
                        {% if form_editar_perfil %}
                        <div class="text-center">Nickname</div>
                            {{form_editar_perfil.nickname}}
                        <br>
                        {% endif %}
                        <div class="row d-flex justify-content-center">
                            <div class="col-sm-2 d-grid gap-2">
                              <input type="button" class="btn btn-dark" value="Atrás" onclick="history.back()">
                            </div>
                            <div class="col-sm-2 d-grid gap-2">
                                <button type='submit' class="btn btn-primary btn-dark">Aceptar</button>
                              </div>
                          </div>
                        </div>
                    </form>
              </div>
          </div>
      </div>
    </div>
</div>
{% endblock %}

PFCharacterCreator/main/templates/perfil/show.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <h5 class="text-center mt-4 mb-4">{{perfil.nickname}}</h5>
  <div class="row">
    <div class="col d-flex justify-content-center mx-auto ">
      <ul class="nav nav-pills">
        {% if personajes %}
        <li class="nav-item" role="presentation">
          <button class="nav-link active" id="pills-personajes-tab" data-bs-toggle="pill" data-bs-target="#pills-personajes" type="button" role="tab" aria-controls="pills-personajes" aria-selected="true">Personajes</button>
      </li>
      {% endif %}
      {% if dotes %}
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-dotes-tab" data-bs-toggle="pill" data-bs-target="#pills-dotes" type="button" role="tab" aria-controls="pills-dotes" aria-selected="false">Dotes</button>
    </li>
      {% endif %}
      </ul>
    </div>
  </div>
  <div class="tab-content" id="pills-tabContent">
  {% if personajes %}
    <div class="tab-pane show in active" id="pills-personajes" role="tabpanel" aria-labelledby="pills-personajes-tab">
      <div class="row mt-4">
        <div class="col">
          <div class="row d-flex justify-content-center mx-auto">
            <div class="col-lg-1 d-flex justify-content-center border" style="background-color:#68E4F0;">
              <p>Nombre</p>
            </div>
            <div class="col-lg-1 d-flex justify-content-center border" style="background-color:#68E4F0;">
                <p>Raza</p>
            </div>
            <div class="col-lg-1 d-flex justify-content-center border" style="background-color:#68E4F0;">
              <p>Clase</p>
          </div>
            <div class="col-lg-1 d-flex justify-content-center border" style="background-color:#68E4F0;">
              <p>Nivel</p>
          </div>
        </div>
        {% for p in personajes %}
        <div class="row d-flex justify-content-center mx-auto">
          <div class="col-lg-1 d-flex justify-content-center border">
            <a href="/personaje/show/{{personaje.pk}}">{{p.nombre}}</a>
          </div>
          <div class="col-lg-1 d-flex justify-content-center border">
              <p class="align-text-middle">{{p.raza.raza}}</p>
          </div>
          <div class="col-lg-1 d-flex justify-content-center border">
            <p class="align-text-middle">{{p.clase.clase}}</p>
        </div>
          <div class="col-lg-1 d-flex justify-content-center border">
            <p class="align-text-middle">{{p.nivel}}</p>
        </div>
        </div>
          {% endfor %}
      </div>
      </div>
        <div class="container mt-2">
          <ul class="pagination d-flex justify-content-center">
            {% if personajes.has_previous %}
            <li class="page-item"><a class="page-link" href="?page_personaje={{personajes.previous_page_number}}">Anterior</a></li>
            {% endif %}
            {% for num in personajes.paginator.page_range %}
            {% ifequal num personajes.number %}
            <li class="page-item active">
              <span class="page-link">
                {{ num }}
                <span class="sr-only">(current)</span>
              </span>
            </li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page_personaje={{ num }}">{{ num }}</a></button></li>
            {% endifequal %}
            {% endfor %}
            {% if personajes.has_next %}
            <li class="page-item"><a class="page-link" href="?page_personaje={{personajes.next_page_number }}">Siguiente</a></li>
            {% endif %}
          </ul>
          {% endif %}
        </div>
    </div>
  {% if dotes %}
  <div class="tab-pane fade" id="pills-dotes" role="tabpanel" aria-labelledby="pills-dotes-tab">
    <div class="row">
      <div class="col">
        <div class="row">
          <div class="col-lg-2">
            <p>Nombre</p>
          </div>
          <div class="col-lg-1">
              <p>Tipo</p>
          </div>
          <div class="col">
            <p>Descripción</p>
        </div>
      </div>
        {% for d in dotes %}
        <div class="row">
          <div class="col-lg-2 align-self-center">
            <a href="/dote/show/{{d.pk}}">{{d.nombre}}</a>
          </div>
          <div class="col-lg-1 align-self-center">
              <p class="align-text-middle">{{d.tipo}}</p>
          </div>
          <div class="col">
            <p>{{d.descripcion}}</p>
        </div>  
      </div>
        {% endfor %}
      </div>
    </div>
    <div class="container">
      <ul class="pagination d-flex justify-content-center">
        {% if dotes.has_previous %}
        <li class="page-item"><a class="page-link" href="?page_dote={{dotes.previous_page_number }}">Anterior</a></li>
        {% endif %}
        {% for num in dotes.paginator.page_range %}
        {% ifequal num dotes.number %}
        <li class="page-item active">
          <span class="page-link">
            {{ num }}
            <span class="sr-only">(current)</span>
          </span>
        </li>
        {% else %}
        <li class="page-item"><a class="page-link" href="?page_dote={{ num }}">{{ num }}</a></button></li>
        {% endifequal %}
        {% endfor %}
        {% if dotes.has_next %}
        <li class="page-item"><a class="page-link" href="?page_dote={{dotes.next_page_number }}">Siguiente</a></li>
        {% endif %}
      </ul>
      {% endif %}
    </div>
  </div>
</div>
</div>

{% if var == True %}
<div class="container">
<div class="row d-flex justify-content-center mt-4">
  <div class="col-sm-2">
    <a href="/perfil/edit/" class="btn btn-md btn-dark ">Editar nickname</a>
  </div>
  <div class="col-sm-2">
    <a href="/perfil/edit/usuario/" class="btn btn-md btn-dark ">Cambiar usuario</a>
  </div>
  <div class="col-sm-2">
    <a href="/perfil/edit/contrasena/" class="btn btn-md btn-dark ">Cambiar contraseña</a>
  </div>
  <div class="col-sm-2">
    <a href="/perfil/delete/" class="btn btn-md btn-dark ">Borrar cuenta</a>
  </div>
</div>
</div>
{% endif %}
{% if perfil.personaje_set.all %}
<div class="container">
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>

    <h2 class="text-center mb-2 mt-4">Clases favoritas</div>
      <div class="d-flex justify-content-center">
      <canvas id="myChart" width="700" height="225"></canvas>
    </div>
  </div>
{% endif %}
<div class="container mt-3">
  <div class="row d-flex justify-content-center">
    <div class="col-sm-1 d-grid gap-2">
      <a href="/" class="btn btn-md btn-dark ">Atrás</a>
    </div>
  </div>
</div>
      <script>
        var ctx = document.getElementById("myChart");
var myChart = new Chart(ctx, {
  type: 'pie',
  data: {
    labels: ['Bárbaro', 'Bardo', 'Clérigo', 'Druida', 'Explorador', 'Guerrero', 'Hechicero', 'Mago', 'Monje', 'Paladín', 'Pícaro'],
    datasets: [{
      data: ["{{num_barbaro}}","{{num_bardo}}", "{{num_clerigo}}", "{{num_druida}}", "{{num_explorador}}", "{{num_guerrero}}", "{{num_hechicero}}", "{{num_mago}}", "{{num_monje}}", "{{num_paladin}}", "{{num_picaro}}"],
      backgroundColor: [
        'rgba(110, 44, 0, 0.9)',
        'rgba(250, 128, 114, 0.9)',
        'rgba(244, 208, 63, 0.9)',
        'rgba(24, 106, 59, 0.9)',
        'rgba(46, 64, 83, 0.9)',
        'rgba(230, 126, 34, 0.9)',
        'rgba(142, 68, 173, 0.9)',
        'rgba(41, 128, 185, 0.9)',
        'rgba(192, 57, 43, 0.9)',
        'rgba(26, 188, 156, 0.9)',
        'rgba(112, 123, 124, 0.9)',
      ],
      borderColor: [
        'rgba(110, 44, 0, 1)',
        'rgba(250, 128, 114, 1)',
        'rgba(244, 208, 63, 1)',
        'rgba(24, 106, 59, 1)',
        'rgba(46, 64, 83, 1)',
        'rgba(230, 126, 34, 1)',
        'rgba(142, 68, 173, 1)',
        'rgba(41, 128, 185, 1)',
        'rgba(192, 57, 43, 1)',
        'rgba(26, 188, 156, 1)',
        'rgba(112, 123, 124, 1)',
      ],
      borderWidth: 1
    }]
  },
  options: {
   	//cutoutPercentage: 40,
    responsive: false,

  }
});
      </script>
      
    
{% endblock %}